remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
title: CAPTCHA rules
description: When and why the Service shows CAPTCHA, the rules we use, and where to find / change related settings.
